spring:
  jpa:
    open-in-view: 'false'
    show-sql: 'true'
    hibernate:
      ddl-auto: 'update'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: 'true'

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    password: sa
  h2:
    console:
      enabled: 'true'
      path: /h2-console

  jpa:
    open-in-view: 'false'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: 'update'
   mvc:
     pathmatch:
       matching-strategy: ant-path-matcher
   h2:
     console:
       enabled: 'true'
       path: /h2-console


  datasource:
    username: root
    password: 43824382
    url: jdbc:mysql://localhost:3306/dbcharta


  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

server:
  port: 8080

# Api-Fixer KEY:
api.key.fixer: QNqvHM1Rf3JjtimxQtMsqj0SXIqlXy7G
api.url.fixer: https://api.apilayer.com/fixer/
api.header-field.fixer: apikey

# Api-SendGrid KEY:
api.key.sendgrid: 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
api.template.welcome.id: d-8122d24f998441f0a6402518dd9276f6
app.email: lucaslopezd@hotmail.com
app.type.email: text/html
app.subject.email: CHARTA te da la Bienvenida!!
app.content.message.email: Email de Bienvenida