spring:
  jpa:
    open-in-view: 'false'
    show-sql: 'true'
    hibernate:
      ddl-auto: 'update'
    database-platform: org.hibernate.dialect.MySQL8Dialect
    #    properties:
    #      hibernate:
    #        dialect: org.hibernate.dialect.H2Dialect
    #        format_sql: 'true'

  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/charta
    driverClassName: com.mysql.cj.jdbc.Driver
#  h2:
#    console:
#      enabled: 'true'
#      path: /h2-console
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

server:
  port: 8080

# Api-Fixer KEY:
api.key.fixer: QNqvHM1Rf3JjtimxQtMsqj0SXIqlXy7G
api.url.fixer: https://api.apilayer.com/fixer/
api.header-field.fixer: apikey

# Api-SendGrid KEY:
api.key.sendgrid: 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
api.template.welcome.id: d-8122d24f998441f0a6402518dd9276f6
app.email: lucaslopezd@hotmail.com
app.type.email: text/html
app.subject.email: CHARTA te da la Bienvenida!!
app.content.message.email: Email de Bienvenida