#spring:
#  jpa:
#    open-in-view: 'false'
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
#        format_sql: 'true'
#    show-sql: 'true'
#    hibernate:
#      ddl-auto: update
#  datasource:
#    username: sa
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    password: sa
#  h2:
#    console:
#      enabled: 'true'
#      path: /h2-console
#  mvc:
#    pathmatch:
#      matching-strategy: ant-path-matcher

spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/dbcharta
    password: 43824382
  jpa:
    hibernate:
      ddl-auto: 'update'

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

server:
  port: 8081

# Api-Fixer KEY:
api.key.fixer: QNqvHM1Rf3JjtimxQtMsqj0SXIqlXy7G
api.url.fixer: https://api.apilayer.com/fixer/
api.header-field.fixer: apikey